console.log('keys',Object.keys({nome:'DavidMarques'}))
console.log('values',Object.keys({nome:'DavidMarques'}))
console.log('now',Date.now())
console.log('random',Math.random())
console.log('global',global)